oxqnd-jin/army_venture_backend

- db/migrations/20240512151353_create_table_user_statuses.sql
- db/migrations/20240512174345_create_table_units.sql
- db/migrations/20240512175740_create_table_rating_criteria.sql
- db/migrations/20240512175903_create_table_place_types.sql
- db/migrations/20240512175934_create_table_places.sql
- db/migrations/20240512180011_create_table_holidays.sql
- db/migrations/20240512180118_create_table_users.sql
- db/migrations/20240512180239_create_table_place_reviews.sql
- db/migrations/20240512180328_create_table_review_scores.sql
- db/migrations/20240512180528_create_table_events_and_promotions.sql
- db/migrations/20240512181315_create_table_user_courses.sql
- db/migrations/20240512181406_create_table_places_in_users_courses.sql
- db/migrations/20240512181640_create_table_event_images.sql
- db/migrations/20240512181646_create_table_place_images.sql
- db/migrations/20240512181931_create_table_suspicious_access_logs.sql
- db/schema.sql
- server.js
- 240513까지 작성된 테이블 migrations 작성
- 서버 작동 메세지 글자깨짐 수정 (윈도우 쪽도 확인바람)
- 아마 dbmate 다운 받아야 migrations 잘 될것임 (맥은 brew install dbmate)
- `dbmate up` 하면 마이그레이션 가능
> [ADD/MODIFY] db migratinos 작성/ 자잘한 코드 수정

- routes/index.js
> [MODIFY] 자잘한 수정

- db/migrations/20240512175934_create_table_places.sql
> [MODIFY] place migrations tel 추가

- models/placeDao.js
- services/placeService.js
- placeDetail GET 리뷰, 사진 추가
- 근데 json array 쪽에 \"로 출력되는 문제가 있음
> [ADD] placeDetail 리뷰, 사진 추가(아직 부족함)

- app.js
- config/oauth.js
- controllers/authController.js
- package-lock.json
- package.json
- routes/authRouter.js
> [Update] Google oauth 2.0

- controllers/eventController.js
- controllers/index.js
- models/data-source.js
- models/eventDao.js
- models/index.js
- routes/eventRouter.js
- routes/index.js
- services/eventService.js
- services/index.js
- event 전체 조회 get
- event detail 조회 get (event_images 포함)
> [ADD] event 조회 기능 추가

- db/migrations/20240512175740_create_table_rating_criteria.sql
- db/migrations/20240512180328_create_table_review_scores.sql
- db/migrations/20240515140423_create_table_place_rating_criterias.sql
- db/schema.sql
- models/placeDao.js
- place_rating_criterias 테이블 추가(장소 별 리뷰 항목 저장, 항목 별 점수 저장, 리뷰 수 저장)
- rating_criterias 복수형으로 변경
- 간단한 코드 수정
> [MODIFY] place_rating_criterias 추가 및 FK 수정

- controllers/placeController.js
- db/migrations/20240515140423_create_table_place_rating_criterias.sql
- db/schema.sql
- models/placeDao.js
- routes/index.js
- routes/placeRouter.js
- services/placeService.js
- 장소 holiday 쉬는지 확인 api 작성
- api 조회시 holiday 알려줌
> [ADD] holiday check

- db/migrations/20240512181317_create_table_with_who.sql
- db/migrations/20240512181318_create_table_user_courses.sql
- db/schema.sql
- 코스 with_who 테이블 추가
- 코스 테이블에 with_who_id 칼럼 추가
> [MODIFY] 코스 테이블 수정

- db/migrations/20240512181318_create_table_user_courses.sql
- db/migrations/20240516032901_create_table_course_likes.sql
- db/schema.sql
> [ADD] 코스 like 추가

- controllers/courseController.js
- models/courseDao.js
- routes/courseRouter.js
- routes/index.js
- services/courseService.js
- course 전체 get api 작성
- course id별 get api 작성
> [ADD] course get api 작성

- controllers/courseController.js
- models/courseDao.js
- routes/courseRouter.js
- services/courseService.js
- 코스 CRUD
- places_in_courses CRUD
- delete, patch 전 유저 확인
- 미유효 유저 접근 차단 확인 필요
> [ADD] 코스 관련 CRUD 추가

- controllers/courseController.js
- models/courseDao.js
- routes/courseRouter.js
- services/courseService.js
- 코스 좋아요 Create, Delete 추가
- 코스 소유자 확인 로직 수정
- 기타 오류 메세지 등 로직 수정
> [ADD/MODIFY] 코스 좋아요 CD 추가/ 코스 소유자 확인 및 여러 로직 오류 수정

- controllers/authController.js
- controllers/courseController.js
- models/courseDao.js
- routes/courseRouter.js
- services/courseService.js
- 동행자 별로 코스 좋아요 내림차순으로 get
- 유저 확인 로직 꼬인거 수정
> [ADD/MODIFY] 동행자 별 코스 좋아요 getFeature courses/ 유저 확인 로직 수정

- db/migrations/20240512180239_create_table_place_reviews.sql
- db/migrations/20240512180328_create_table_review_scores.sql
- db/migrations/20240512181318_create_table_user_courses.sql
- db/migrations/20240512181406_create_table_places_in_users_courses.sql
- db/migrations/20240512181640_create_table_event_images.sql
- db/migrations/20240512181646_create_table_place_images.sql
- db/migrations/20240515140423_create_table_place_rating_criterias.sql
- db/migrations/20240516032901_create_table_course_likes.sql
- 로직 상, on delete cascade 필요한 부분들 추가
> [MODIFY] ON DELETE CASCADE 추가

- controllers/userController.js
- models/userDao.js
- routes/index.js
- routes/userRouter.js
- services/userService.js
> [ADD] 유저 조회

- db/migrations/20240512180118_create_table_users.sql
> [MODIFY] 유저 테이블에 nickname 추가

- controllers/userController.js
- models/userDao.js
- routes/userRouter.js
- services/userService.js
> [ADD] 유저 수정, 삭제

- db/migrations/20240512180328_create_table_review_scores.sql
- db/migrations/20240521002918_create_table_withdraw_reasons.sql
- db/migrations/20240521003421_create_table_other_withdraw_resons.sql
- db/schema.sql
- 객관식 탈퇴 사유 테이블 추가 (선택된 횟수 저장)
- 주관식 탈퇴 사유 테이블 추가
> [ADD] 탈퇴 사유 테이블 추가

- controllers/userController.js
- models/userDao.js
- services/userService.js
- 유저 탈퇴 시 탈퇴 사유 묻는 로직 추가
- 기타 사유는 서술형 응답 별도로 저장
> [MODIFY] 탈퇴 사유 추가
